### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by loydjayme25** [ddwhan0123/Useful-Open-Source-Android#5]
hello sir, i am a graphics designer and i am willing to work for your project logo.

**Comment by ddwhan0123** [comment]
Very welcome @loydjayme25

**Comment by loydjayme25** [comment]
okay sir, i will make a design for you. Thank You !

**Comment by ddwhan0123** [comment]
I look forward to your design @loydjayme25

**Comment by loydjayme25** [comment]
The open source logo in on the center of android since the project is all about android .

![proposal](https://user-images.githubusercontent.com/37318022/40596336-b4fdd276-626c-11e8-8a90-7d0edea8a2a6.png)
