### ISSUE TITLE
The design proposal

### ISSUE THREAD

**Issue by loydjayme25** [ddwhan0123/Useful-Open-Source-Android#6]
Open source logo in on the center of the android logo since the project is all about android :)

![proposal](https://user-images.githubusercontent.com/37318022/40596353-d5c8cd08-626c-11e8-9ee5-e7b970a12eb3.png)

**Comment by ddwhan0123** [comment]
Thanks,I upload the logo already.

**Comment by loydjayme25** [comment]
i will send a Pull Request for the sizes and the Project Banner for a good outlook.

**Comment by ddwhan0123** [comment]
@loydjayme25 ok  ,i will update soon

**Comment by loydjayme25** [comment]
I already sent a PR. pls do check :)

**Comment by ddwhan0123** [comment]
@loydjayme25 OK
